---
title: "Week 6/7 Workshop - Chaff"
author: Emily Fradley
output:
  bookdown::html_document2: default
bibliography: chaffref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE,
                      fig.retina = 3)
```

```{r packages}
library(tidyverse)
library(bookdown)
```

#Introduction
Chaffinches (*Fringilla coelebs*) are one of the most wide spread and abundant birds in Britian [@noauthor_undated-dq]. 

#Methods
This is the methods
```{r import data}
# the working directory is in the scripts folder
# had to use backwards relative path to get to data
chaff_raw <- read.table("../data_raw/chaff.txt", header = T)
```

```{r tidy data}
chaff_tidy <- pivot_longer(data = chaff_raw,
                           cols = everything(),
                           names_to = "sex",
                           values_to = "mass")
```

```{r create sumsq function}
# the double braces are used to indicate a column of a dataframe
sum_sq <- function(df, measure, group) {
  df %>% group_by({{ group }}) %>% 
    summarise(ss = sum(({{measure}} - mean({{measure}}))^2))
}

sum_sq(chaff_tidy, mass, sex)
```

#Results

```{r summary function}
# create function that summarizes data and includes
# mean, sd, smaple size, se
data_summary <- function(df, measure, group){
 df %>% group_by({{group}}) %>% 
  summarise(mean = mean({{measure}}),
            n = length({{measure}}),
            sd = sd({{measure}}),
             se = sd/sqrt(n))
}

data_summary(chaff_tidy, mass, sex)
```


#Disscussion